version: '3.8'
services:
  web:
    container_name: fastapi
    build: .
    restart: always
    env_file: .env
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    volumes:
     - .:/app
    ports:
      -  5000:5000