name: master

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [postgres]
        python-version: [3.11.x]

    services:
      postgres:
        image: postgres:13.5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  aws-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SSH to Instance
      env:
        AWS_PRIVATE_KEY: irohaxi.pem
        AWS_HOSTNAME: 18.197.38.72
        AWS_USERNAME : ubuntu

      run: |
          chmod 600 ${AWS_PRIVATE_KEY}
          ssh -o StrictHostKeyChecking=no -i irohaxi.pem ${AWS_USERNAME}@${AWS_HOSTNAME} '
            # 📌 Start your instance/server related tasks form here.
            bash ~/.scripts/docker-deploy.sh
          '